- lib/Pages/signup.dart
I think we can take further information from the profile tag or when applying for donation about blood group, diseases, reports, medical reports etc...
> updated the signup page

- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/cubit/profile_cubit.dart
- lib/cubit/profile_state.dart
- lib/main.dart
- lib/views/pages/login/login.dart
- lib/views/pages/main_home/bottom_nav.dart
- lib/views/pages/main_home/homepage.dart
- lib/views/pages/profile/profile_screen.dart
- lib/views/pages/register/signup.dart
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- macos/Podfile
- pubspec.lock
- pubspec.yaml
Pros: Now when a user registers he can go to profile and edit his basic medical information of patient.
Cons : Not able to reproduce the data when the user logs back in.
> Screen for User Profile Setup #15

- lib/views/pages/register/signup.dart
**Issue:** #19 
I have added a **IconButton** on the top right corner of **Sign Up** page to navigate back to the **Front Page**. For this I added an **AppBar** and a leading button on **AppBar** to Navigate back and I works completely fine.
**Before the update:**
**After the Update:**
> Addition: Navigate Back Button on Sign Up Page

- lib/views/pages/locateBloodbank/locateBloodBank.dart
- lib/views/pages/main_home/home_pages/home_screen.dart
**Created Page for Locate BloodBank.**
- This page is currently blank as API is under maintenence
- This page will have api retrieved infos
- This partially solves #13
> Created Page for Locate BloodBank

- README.md
solved #34 Added all .md links to main readme file
> fixed all .md links to main readme file 

- README.md
with respect to closed pr fixed all .md links to main readme file #35
i made more changes can you add level label now
issue #34
> modifications made

- lib/views/pages/register/signup.dart
For the Issue : Input Validation during SignUp #33
I have added validation as discussed without making changes to backend code. 
Kindly review and let me know if any thing needs to be changed.
> In Sign Up Page Added validation for Email,Password,Phone Number

- .github/workflows/greetings.yml
> Create workflow yml file

- lib/Utils/validation_helpers.dart
- lib/main.dart
- lib/models/verification_status.dart
- lib/services/verification_service.dart
- lib/views/verificationform.dart
- pubspec.yaml
> Added Donor and Recipient Verification System

- android/app/src/main/AndroidManifest.xml
- android/settings.gradle
- ios/Runner/Info.plist
- lib/views/pages/camps/campsPage.dart
- lib/views/pages/main_home/homepage.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
Implemented a new page dedicated to displaying nearby blood donation camps.
Added functionality for users to view details about each camp, including name, date, time, and location.
these are some sample images you can check it out and review my code and make sure to replace mongo db URI to yours. 
fixes #14
> Added Camp Page (Fixes #14)

- lib/cubit/forgot_password/forgot_password_cubit.dart
- lib/cubit/forgot_password/forgot_password_state.dart
- lib/views/pages/forgot_password/change-password.dart
- lib/views/pages/forgot_password/forgot-password.dart
- lib/views/pages/login/login.dart
#58 
https://github.com/user-attachments/assets/4b82d574-c850-48b9-904c-b378fc7291d7
> forgot password functionality integrated

- lib/views/pages/welcome/welcome_screen.dart
This pull request introduces an enhancement to the FrontPage widget of the DonorConnect application. The following changes have been made:
- **Authentication Check**: Implemented a FutureBuilder to check the user's authentication status using Firebase Auth. This ensures that users who are already logged in are automatically redirected to the HomePage without needing to click on the login or signup buttons.
- **Loading Indicator**: Added a loading indicator to provide feedback to users while the app determines the authentication state.
- **User Experience Improvement**: If the user is not logged in, the app displays options to log in or sign up, maintaining a seamless experience.
**Benefits**: This enhancement improves user experience by reducing unnecessary clicks and streamlining the …
> Implement Auto-Redirect to Homepage Based on User Authentication Status

- lib/views/pages/profile/profile_screen.dart
i have changed the form on profile screen and syling and color was not correct i used theme color and styling .
> changed form styling and and save button styling in profile screen

- .github/workflows/build_apk.yml
> Added build apk action

- lib/views/pages/camps/campsPage.dart
i have changed the addform styling in campus page
> changed the addform styling in campus page

- lib/cubit/theme_toggle/theme_cubit.dart
- lib/cubit/theme_toggle/value_cubit.dart
- lib/main.dart
- lib/views/common_widgets/toggle_button.dart
- lib/views/pages/profile/profile_screen.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
> added toggle button to toggle b/w light and dark theme

- lib/views/pages/forgot_password/change-password.dart
- lib/views/pages/forgot_password/forgot-password.dart
- pubspec.lock
i have change the styling of forget password screen buttons
> change the styling of forget password screen buttons

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/firebase_options.dart
- lib/views/pages/learn_about_donation/learn_about_donation.dart
- lib/views/pages/main_home/home_pages/home_screen.dart
- Implemented a new page providing detailed information on blood and platelet donation.
- Included helpful links to Indian Government resources (NBTC, Ministry of Health, E-RaktKosh) and international organizations.
- Refactored code into reusable widgets for efficiency.
https://github.com/user-attachments/assets/7faf7532-1e17-48a8-80d2-e8295d54dc91
> Added 'Learn More About Blood and Platelet Donation' Page

- PROJECT_STRUCTURE.md
- lib/views/common_widgets/donor_card.dart
- lib/views/common_widgets/rounded_conatiner.dart
- lib/views/common_widgets/rounded_image.dart
- lib/views/pages/Required/required_screen.dart
- lib/views/pages/Required/widgets/choice_chip.dart
- lib/views/pages/main_home/home_pages/home_screen.dart
- repo_structure.txt
i have added  have added folders as shown below:- 
in common folder
lib/views/common_widgets/donor_card.dart
lib/views/common_widgets/rounded_conatiner.dart
lib/views/common_widgets/rounded_image.dart
lib/views/pages/Required/
changed home onpressed to Required Screen
> added screen for  required button on home page

- lib/views/pages/camps/campsPage.dart
- lib/views/pages/register/signup.dart
Fix #71 
@prajapatihet 
Issue on singup page resolved.
Please find Screenshot to verfiy.
Do tell if there is any other issue on which i can work on.
> Signup page issue resolved

- lib/cubit/theme_toggle/theme_cubit.dart
- lib/cubit/theme_toggle/theme_state.dart
- lib/cubit/theme_toggle/value_cubit.dart
- lib/main.dart
- lib/views/common_widgets/toggle_button.dart
- lib/views/pages/profile/profile_screen.dart
#105 
https://github.com/user-attachments/assets/9015f1df-6f78-44bd-9c06-304a2bd19049
Overview: 
This pull request implements an enhanced theme management system in the project .The new implementation allows for dynamic theme switching based on application states, ensuring a consistent user experience that aligns with the system theme.
Key Changes:
Added a theme selection feature that allows users to toggle between light and dark modes, aligning with the user's system theme preferences.
Updated the UI to reflect the current theme based on the state managed by BLoC.
Improved code organization and readability by separating theme logic into its own BLoC.
Benefits:
Provides a seamless user experience with theme adaptability.
Enhances maintainability and scalability of the theme management …
> Handling Correctly the Application Theme

- README.md
**Description:**
I’ve added a Back to Top link for easier navigation within the README file. At the bottom of each main section, you’ll find a Back to Top link that will take you back to the beginning of the document.
*********************
**Screenshot/Preview:**
*********************
@prajapatihet Please review and merge it under gssoc-ext level1 and hacktoberfest lables.
> Added back-to-top button to README.md
